[package]
name = "pyscythe_pyproject"
description = "Reads pyproject.toml into the pyscythe manifest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
pyscythe_core = { workspace = true }

camino = { workspace = true }
ruff_python_ast = { workspace = true }
ruff_python_parser = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
