#!/usr/bin/env bash
# Render the tap formula for a released version from the archives
# packaging/binaries.sh built. The tap is jacobsieradzki/homebrew-tap, so the
# formula file it writes is Formula/pyscythe.rb there.
#
#   packaging/homebrew.sh VERSION ARCHIVE_DIR > Formula/pyscythe.rb
set -euo pipefail

version=${1:?usage: homebrew.sh VERSION ARCHIVE_DIR}
archives=${2:?usage: homebrew.sh VERSION ARCHIVE_DIR}
sums="$archives/SHA256SUMS"

sum_for() {
  local sum
  sum=$(awk -v want="$1" '$2 == want || $2 == "./" want { print $1 }' "$sums")
  if [ -z "$sum" ]; then
    echo "no checksum for $1 in $sums" >&2
    return 1
  fi
  printf '%s' "$sum"
}

macos_arm=$(sum_for "pyscythe-$version-aarch64-apple-darwin.tar.gz") || exit 1
macos_intel=$(sum_for "pyscythe-$version-x86_64-apple-darwin.tar.gz") || exit 1
linux_arm=$(sum_for "pyscythe-$version-aarch64-unknown-linux-gnu.tar.gz") || exit 1
linux_intel=$(sum_for "pyscythe-$version-x86_64-unknown-linux-gnu.tar.gz") || exit 1

download="https://github.com/jacobsieradzki/pyscythe/releases/download/v$version"

cat <<RUBY
# Generated by packaging/homebrew.sh in jacobsieradzki/pyscythe. Do not edit.
class Pyscythe < Formula
  desc "Dead code, import cycles, duplication, and complexity for Python codebases"
  homepage "https://github.com/jacobsieradzki/pyscythe"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$download/pyscythe-$version-aarch64-apple-darwin.tar.gz"
      sha256 "$macos_arm"
    end
    on_intel do
      url "$download/pyscythe-$version-x86_64-apple-darwin.tar.gz"
      sha256 "$macos_intel"
    end
  end

  on_linux do
    on_arm do
      url "$download/pyscythe-$version-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$download/pyscythe-$version-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_intel"
    end
  end

  def install
    bin.install "pyscythe"
  end

  test do
    assert_match "pyscythe #{version}", shell_output("#{bin}/pyscythe --version")

    (testpath/"pkg/__init__.py").write ""
    (testpath/"pkg/dead.py").write "def never_called():\n    return 1\n"
    # A finding is exit code 1, which is the point of the tool.
    assert_match "pkg.dead", shell_output("#{bin}/pyscythe dead-code #{testpath}", 1)
  end
end
RUBY
